FROM jupyter/base-notebook:latest

USER root

WORKDIR /app

RUN apt-get update && apt install build-essential -y

RUN pip install -r requirements3.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=pepperdev"]
