FROM jupyter/base-notebook:latest

USER root

WORKDIR /app

RUN pip install gpt4all
RUN pip install langchain
RUN apt-get update -y && apt install build-essential
RUN pip install chromadb
RUN pip install llama-cpp-python

#RUN wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=pepperdev"]
